import axios from 'axios';
import * as coreui from '@coreui/coreui-pro';
window.axios = axios;
window.coreui = coreui;
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

import '@coreui/utils/dist/umd/index';
import 'simplebar';
import './color-modes';
import './locale-modes';
import './colors';
import './config';
import './popovers';
import './toasts';
import './tooltips';
import '../icons/free.svg';
import '../icons/brand.svg';
import '../icons/duotone.svg';
import '../icons/flag.svg';
import '../icons/linear.svg';
import '../icons/solid.svg';
